library(flowCore)
library(BiocManager)
library(tidyFlowCore)
library(reshape2)
library(readxl)
library(openxlsx)
library(readr)
library(data.table)
#library(stringr)
library(plyr)
library(dplyr)
library(networkD3)
library(Hmisc)
library(igraph)
library(plotly)
#library(tidyverse)
library(tcltk)
#library(stringr)


result_folder <- tk_choose.dir(caption = "choose the folder with your candidates")
file_name = paste(result_folder,"\\hello_world",sep = "")
print("hello")
print(file_name)
write("hello", file_name)

